### ISSUE TITLE
MS Spectra format

### ISSUE THREAD

**Issue by NabilaRahman** [gatechatl/JUMPg#3]
Hi,
I'm new to this and I was wondering if the MS spectra file has to be .mzXML. Because I get a  .raw spectra file from running MS-MS on Thermo instruments. Will JumpG use this format?

Also I have multiple samples representing a timecourse, would you recommend merging the vcf and SJ.out.tab files for them?

**Comment by liyuxin-bioinformatics** [comment]
Hi,

JUMPg currently only supports .mzXML format. To proceed, you have to convert the .raw files into mzXML format using tools such as ReAdW (http://tools.proteomecenter.org/wiki/index.php?title=Software:ReAdW) or other similar tools.

There is no perfect answer whether to merge genomics information (in this case, vcf and SJ.out.tab files) of multiple samples to construct customized database: it's always a trade-off between sensitivity and specificity. While merging may give better sensitivity (e.g., due to false negatives for SNV calling in one sample, but re-covered in another), building sample-specific database gives better specificity (which better prevents false spectrum-peptide matching, and also saves running time because of smaller search space for each sample). In practice, it really depends on your situation. For example, if each .vcf file is very small (e.g., a couple hundreds of non-silent variants), and you only have a few samples (e.g., <10), you may merge them for a single customized database for your convenience. But it may be a totally different story if you have very large sample size (e.g., hundreds of samples) or consider many variants (e.g., hundreds of thousands). 

BTW, we will not update this site anymore and Please try our latest version under our new site: https://github.com/liyuxin-bioinformatics/JUMPg

Thanks for your interest in our software.

Yuxin

**Comment by NabilaRahman** [comment]
Sorry for the late reply. This solves my issue and many thanks for your valuable input
